spring.application.name: discovery

---
spring:
  profiles: local

server:
  port: 18081

eureka:
  instance:
    hostname: local
  client:
    serviceUrl.defaultZone: http://localhost:18081/eureka/
    registerWithEureka: false
    fetchRegistry: false